import { Product } from "./types";
import productsJson from "@/data/products.json";
import tilbudJson from "@/data/tilbud.json";

// Products are stored in src/data/products.json
// Generated by running the CSV import script — never edit manually

interface TilbudOverlayEntry {
  butik: string;
  kategori: string;
  produktnavn: string;
  tilbudsPris: number;
  foerPris?: number;      // original ("før")-pris fra avisen — valgfri, bruges til "Spar X"
  maengde: number;
  maengdeEnhed: string;
  vegetar?: boolean;
  maerke?: string;
}

const tilbudOverlay = tilbudJson as TilbudOverlayEntry[];

// Ugentligt tilbuds-overlay — tilbud matches på KATEGORI, ikke på produktnavn.
// Hvert tilbud tilføjes som en kandidat-vare i sin kategori (paTilbud: true,
// normalPris = tilbudsPris) uden at røre products.json. findBestOption() vælger
// derefter billigste total i kategorien, så en tilbudsvare vinder hvis den er
// billigere end de normale varer — og udregner "Spar" mod billigste ikke-tilbud.
// Opdateres manuelt hver uge i src/data/tilbud.json. Tom ([]) = ingen aktive
// tilbud. Skal på sigt udskiftes med automatisk scraping.
function applyTilbudOverlay(products: Product[]): Product[] {
  if (tilbudOverlay.length === 0) return products;
  const tilbudProducts: Product[] = tilbudOverlay.map((o) => ({
    butik: o.butik,
    kategori: o.kategori,
    produktnavn: o.produktnavn,
    normalPris: o.tilbudsPris,
    maengde: o.maengde,
    maengdeEnhed: o.maengdeEnhed,
    vegetar: o.vegetar ?? false,
    paTilbud: true,
    ...(o.foerPris ? { foerPris: o.foerPris } : {}),
    ...(o.maerke ? { maerke: o.maerke } : {}),
  }));
  return [...products, ...tilbudProducts];
}

// Beregnes én gang ved modul-load, ikke ved hvert hook-kald — ellers laver .map()
// et nyt array hver gang useProducts() kaldes, og komponenter der har `products` i en
// useEffect-dependency-liste ender i et uendeligt render-loop ("Maximum update depth exceeded").
const productsWithTilbud = applyTilbudOverlay(productsJson as Product[]);

export function useProducts(): Product[] {
  return productsWithTilbud;
}
