import { Product } from "./types";
import productsJson from "@/data/products.json";
import tilbudJson from "@/data/tilbud.json";

// Products are stored in src/data/products.json
// Generated by running the CSV import script — never edit manually

interface TilbudOverlayEntry {
  butik: string;
  kategori: string;
  produktnavn: string;
  tilbudsPris: number;
}

const tilbudOverlay = tilbudJson as TilbudOverlayEntry[];

// Ugentligt tilbuds-overlay — overlejrer paTilbud + pris på navngivne produkter
// uden at røre products.json. Opdateres manuelt hver uge i src/data/tilbud.json
// (samme felter: butik, kategori, produktnavn, tilbudsPris). Tom ([]) = ingen
// aktive tilbud. Skal på sigt udskiftes med automatisk scraping.
function applyTilbudOverlay(products: Product[]): Product[] {
  if (tilbudOverlay.length === 0) return products;
  return products.map((p) => {
    const match = tilbudOverlay.find(
      (o) => o.butik === p.butik && o.kategori === p.kategori && o.produktnavn === p.produktnavn
    );
    if (!match) return p;
    return { ...p, paTilbud: true, normalPris: match.tilbudsPris };
  });
}

// Beregnes én gang ved modul-load, ikke ved hvert hook-kald — ellers laver .map()
// et nyt array hver gang useProducts() kaldes, og komponenter der har `products` i en
// useEffect-dependency-liste ender i et uendeligt render-loop ("Maximum update depth exceeded").
const productsWithTilbud = applyTilbudOverlay(productsJson as Product[]);

export function useProducts(): Product[] {
  return productsWithTilbud;
}
