import { Product } from "./types";
import productsJson from "@/data/products.json";

// Products are stored in src/data/products.json
// Generated by running the CSV import script — never edit manually
export function useProducts(): Product[] {
  return productsJson as Product[];
}
